unicode characters fix
spatie/7to5 pull request #41
Opened 2018-10-07 01:44 UTC by voku

see issue#40

-> this is a BC because we need a new version of "nikic/php-parser" (PHP >= 7.0)

2018-10-08 08:53 UTC, freekmurze requested changes

2018-10-08 08:53 UTC, freekmurze commented on src/PhpParser/KeepOriginalValuePrinter.php
> +        // DEBUG
Remove all debug code.

2018-10-08 20:13 UTC, voku commented on src/PhpParser/KeepOriginalValuePrinter.php
> +        // DEBUG
Debug code is removed.

2018-10-24 11:09 UTC, freekmurze commented
We are not maintaining this package any more. Feel free to fork our code and maintain your own copy.

2018-10-24 11:09 UTC, closed without merging